# Generated by Django 4.2.5 on 2023-10-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageq',
            old_name='Mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='messageq',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messageq',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='messageq',
            old_name='Subject',
            new_name='subject',
        ),
    ]
