# Generated by Django 4.2.5 on 2023-10-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_rename_mail_messageq_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageQ',
            new_name='Messages',
        ),
    ]
