# Generated by Django 4.2.6 on 2023-10-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_depatrments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Doctorlist')),
                ('doc_name', models.CharField(max_length=100)),
                ('depart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.depatrments')),
            ],
        ),
    ]
