# Generated by Django 4.2.6 on 2023-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_doctorlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlist',
            old_name='depart_name',
            new_name='doc_dep',
        ),
    ]
