# Generated by Django 4.2.6 on 2023-10-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_rename_depart_name_doctorlist_doc_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlist',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
