# Generated by Django 4.2.6 on 2023-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_remove_appointment_time_appointment_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='doc_spec',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
