# Generated by Django 4.2.6 on 2023-10-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_doctorlist_doc_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlist',
            name='doc_spec',
        ),
    ]
