# Generated by Django 4.2.6 on 2023-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0011_remove_doctorlist_doc_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='doc_spec',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
